---
- name: Add WordPress Virtual Host
  copy:
    src: wordpress.local.conf
    dest: /etc/httpd/conf.d/wordpress.local.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Apache

- name: Update default Apache site
  lineinfile: 
    dest: /etc/httpd/conf/httpd.conf 
    regexp: "Listen 80"
    line: "#Listen 80"
  notify:
    - Restart Apache

- name: Copy sample config file
  copy:
    src: /var/www/wordpress/wp-config-sample.php
    dest: /var/www/wordpress/wp-config.php

- name: Update WordPress config file
  lineinfile:
    dest: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', 'wordpress');"}        
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', 'wordpress');"}        
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', 'wordpress');"}
