---
- name: Download WordPress
  get_url: 
    url: https://wordpress.org/latest.tar.gz 
    dest: /tmp/wordpress.tar.gz
    validate_certs: false

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    copy: false

- name: Apply new SELinux file context
  command: restorecon -Rv /var/www/

