---
- name: Install Apache
  yum:
    name:
      - php
      - php-common
      - php-mysql
      - php-gd
      - httpd
    state: present

- name: Start Apache
  systemd:
    name: httpd
    state: started
    enabled: true
